import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen h-screen text-center pt-40 text-black font-bold text-3xl">
        <div>this is a productivity app!</div>
        <Link href={"/login"}>login</Link>
      </div>
    </div>
  );
}
