import React from "react";
import Head from "next/head";
import Link from "next/link";

const login = () => {
  return (
    <div>
      <Head>
        <title>login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="grid grid-cols-12 h-30 mb-10 pt-10 fixed top-10 w-full z-10 drop-shadow-xl">
        <div
          className={`bg-orange text-center p-8 px-16 rounded-3xl text-white text-4xl font-extrabold col-span-10 col-start-2`}
        >
          login
        </div>
      </header>
      <div className="h-[216px] py-10"></div>

      <div className="bg-orange text-center p-6 px-16 mx-16 rounded-3xl text-white text-4xl font-extrabold my-3">
        google
      </div>
      <div className="bg-orange text-center p-6 px-16 mx-16 rounded-3xl text-white text-4xl font-extrabold my-3">
        email
      </div>

      <header className="grid grid-cols-12 mb-10 fixed bottom-3 w-full z-10 drop-shadow-xl">
        <div
          className={`bg-orange text-center p-4 px-16 rounded-3xl text-white text-4xl font-extrabold col-span-8 col-start-3`}
        >
          <Link href={'/'}>&lt; back</Link>
        </div>
      </header>
    </div>
  );
};

export default login;
