import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Project from "../components/Project";
import NewProject from "../components/NewProject";
import MobileHeader from "../components/MobileHeader";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div initial={{ y: -100 }} animate={{ y: 0 }}>
        <Header
          className="sm:hidden"
          name={"projects"}
          left={"pink"}
          middle={"green"}
          right={"blue"}
          leftLink={"schedule"}
          rightLink={"tasks"}
        />
        <MobileHeader name={"projects"} color="green" />

        <Project name={"history doc id"} />
        <Project name={"math test"} />
        <Project name={"english paper"} />
        <NewProject />
      </motion.div>

      <Footer
        left={"col-span-2 row-span-4"}
        middle={"col-span-2 row-span-4"}
        right={"col-span-3 row-span-5"}
      />
    </div>
  );
}
