import React, { useState, useEffect } from "react";
import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Project from "../components/Project";
import NewProject from "../components/NewProject";
import MobileHeader from "../components/MobileHeader";
import { motion } from "framer-motion";

export default function Home() {

  const [projects, setProjects] = useState([
    {
      name: "history doc id",
      date: [9, 12, 22],
      tasks: [1, 2],
    },
    {
      name: "math test",
      date: [9, 12, 22],
      tasks: [4],
    },
  ]);

  return (
    <div>
      <Head>
        <title>projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ y: -100 }}
        animate={{ y: 0 }}
        exit={{ opacity: 0 }}
      >
        <Header
          className="sm:hidden"
          name={"projects"}
          left={"blue"}
          middle={"green"}
          right={"pink"}
          leftLink={"tasks"}
          rightLink={"schedule"}
        />
        <MobileHeader name={"projects"} color="green" topLeftButton={"+"} leftButtonLink="" />

        {projects.map((project) => (
          <Project name={project.name} />
        ))}
        <NewProject setProject={setProjects} projects={projects} />
      </motion.div>

      <Footer
        left={"col-span-2 row-span-4"}
        middle={"col-span-2 row-span-4"}
        right={"col-span-3 row-span-5"}
      />
    </div>
  );
}
