import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Project from "../components/Project";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header name={"projects"} left={"pink"} middle={"green"} right={"blue"} leftLink={"schedule"} rightLink={"tasks"} />

      <Project name={"history doc id"}/>
      <Project name={"math test"}/>
      <Project name={"english paper"}/>
      
      <Footer left={"pink"} middle={"green"} right={"blue"} />
    </div>
  );
}
