import { useState } from "react";
import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import MobileHeader from "../components/MobileHeader";
import { motion } from "framer-motion";
import Schedule from "../components/Schedule";
import ScheduleEdit from "../components/ScheduleEdit";

export default function Home() {
  const [blockOffTimes, setblockOffTimes] = useState([
    [1, 120],
    [12, 60],
    [20, 90],
  ]);
  let blocks = [];
  for (let i = 0; i < blockOffTimes.length; i++) {
    let top = 297 + blockOffTimes[i][0] * 60;
    blocks.push(
      <div
        className={`w-7/12 bg-[#D9D9D9] opacity-80 absolute left-[22%] rounded-xl drop-shadow-lg`}
        style={{ height: blockOffTimes[i][1] + "px", top: top }}
      ></div>
    );
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ y: -100 }}
        animate={{ y: 0 }}
        exit={{ opacity: 0 }}
      >
        <Header
          name={"schedule"}
          left={"green"}
          middle={"pink"}
          right={"blue"}
          leftLink={"projects"}
          rightLink={"tasks"}
        />
        <MobileHeader
          name={"schedule"}
          color="pink"
          topLeftButton={"edit"}
          leftButtonLink="/schedule/edit"
        />

        <div className="grid grid-cols-12 text-center">
          <div className="col-start-2 col-span-3 translate-y-1">yesterday</div>
          <div
            className="font-bold text-3xl col-span-4 -translate-y-1"
            layoutId={"today"}
          >
            today
          </div>
          <div className="col-span-3 translate-y-1">tommorow</div>
        </div>

        <Schedule />
        {blocks}
        {/* <div className=" w-7/12 h-[240px] bg-[#D9D9D9] opacity-80 absolute top-[297px] left-[22%] rounded-xl drop-shadow-lg"></div> */}
        <div className=" w-7/12 h-[60px] bg-blue absolute top-[537px] left-[22%] rounded-xl drop-shadow-lg text-white text-xl font-bold text-center p-4">
          english homework
        </div>
      </motion.div>

      <Footer
        left={"col-span-3 row-span-5"}
        middle={"col-span-2 row-span-4"}
        right={"col-span-2 row-span-4"}
      />
    </div>
  );
}
