import React, { useState } from "react";
import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Day from "../components/Day";
import Task from "../components/Task";
import NewTask from "../components/NewTask";
import MobileHeader from "../components/MobileHeader";
import { motion, AnimatePresence } from "framer-motion";

export default function Home() {
  const [tasks, setTasks] = useState([
    ["english reading", 60, 9, 11, 22],
    ["math hw", 200, 9, 12, 22], 
  ]);
  const [inputValue, setInputValue] = useState(["", 30, 0, 0, 0]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div initial={{ y:-100 }} animate={{y:0}} exit={{x:100}}>
        <Header
          name={"tasks"}
          left={"green"}
          middle={"blue"}
          right={"pink"}
          leftLink={"projects"}
          rightLink={"schedule"}
        />
        <MobileHeader name={"tasks"} color="blue" />

        <Day day={"today"} />
        {tasks.map((task) => (
          <Task name={task[0]} />
        ))}
        <NewTask />

        <Day day={"today"} />
        {tasks.map((task) => (
          <Task name={task[0]} />
        ))}
        <NewTask />
        <Day day={"today"} />
        {tasks.map((task) => (
          <Task name={task[0]} />
        ))}
        <NewTask />
        <Day day={"today"} />
        {tasks.map((task) => (
          <Task name={task[0]} />
        ))}
        <NewTask />
      </motion.div>

      <Footer
        left={"col-span-2 row-span-4"}
        middle={"col-span-3 row-span-5"}
        right={"col-span-2 row-span-4"}
      />
    </div>
  );
}
